name: CD Update

run-name: ft_libft CD Update deployment

on:
  workflow_call:

jobs:
  update-ft_libft:
    runs-on: ubuntu-latest
    steps:
      - name: ☁️ Retrieve ft_libft repo
        uses: actions/checkout@v3
        with:
          repository: "Pixailz/ft_libft"
          submodules: recursive
          token: ${{ secrets.PAT_ACTIONS }}

      - name: ☁️ Update submodules
        run: git submodule update --remote --recursive

      - name: 🔧 Update file with helper
        run: make helper

      - name: ☁️ Configure, commit and push
        run: |+
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add . || true
          git commit -m "[helper] submodule update spread" || true
          git status && git push || true
