name: CD

run-name: ft_libft CD deployment

on:
  workflow_call:

jobs:
  git_release:
    runs-on: ubuntu-latest
    steps:
      - name: ☁️ Retrieve repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: 🔧 Build up libft.a
        run: DISABLE_HELPER=1 make re

      - name: 🔧 Declare some var
        run: |+
          {
            echo "sha7=${GITHUB_SHA::7}"
            printf "ver=%s" \
            "$(perl -nE 'print if s|VERSION\s+:= (\d\.\d\.\d)|\1|gm' ./mk/config.mk)"
          } >> ${GITHUB_ENV}

      - name: ☁️ Upload release artifact
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          draft: false
          prerelease: true
          name: build ${{ env.sha7 }}
          tag_name: v${{ env.ver }}-${{ env.sha7 }}
          files: |
            libft.a
            inc/**
          token: ${{ secrets.GITHUB_TOKEN }}
