name: CI

run-name: Library build and test CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "github"
        run: |+
          echo "Who launched: ${{github.actor}}"
          echo "On branch:    ${{github.ref_name}}"
          echo "Commit sha:   ${{github.sha}}"
          cat .git/config

      - name: "Bin utils"
        run: |+
          make --version && echo
          ar --version && echo
          gcc --verbose && echo
          python3 --version

  build:
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build up libft.a (${{ matrix.os }})
        run: CI_TEST=1 make

      - name: Call some Makefile rules
        run: |+
          CI_TEST=1 make fclean
          CI_TEST=1 make re
          CI_TEST=1 make

      - name: Call helper
        run: |+
          make helper

  test:
    strategy:
      max-parallel: 5
      matrix:
        test_src: [
          "ato.c",
          "check/is_str.c",
          "get_next_line.c",
          "int4.c",
          "ipv4.c",
          "isexec.c",
          "print_nb_base.c",
          "random.c",
          "tmpfile.c"
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: launch ${{ matrix.test_src }}
        run: CI_TARGET=${{ matrix.test_src }} make ci-run

